[phases.setup]
nixPkgs = ["pkgs.python313Full", "pkgs.yt-dlp", "pkgs.ffmpeg"]

# Si también usas Node.js, Nixpacks normalmente lo detecta automáticamente,
# pero puedes especificar la versión si es necesario.
# nixPkgs = ["pkgs.python313Full", "pkgs.yt-dlp", "pkgs.ffmpeg", "pkgs.nodejs_20"]
